export const FONTS =     [
    {key:'1',value: 'Arbutus', text:'Arbutus'},
    {key:'2',value: 'Bangers', text:'Bangers'},
    {key:'3',value: 'Bungee', text:'Bungee'},
    {key:'5',value: 'CodyStar', text:'CodyStar'},
    {key:'6',value: 'Creepster', text:'Creepster'},
    {key:'7',value: 'Diplomata', text:'Diplomata'},
    {key:'8',value: 'Eater', text:'Eater'},
    {key:'9',value: 'Ewert', text:'Ewert'},
    {key:'10',value: 'FasterOne', text:'Faster One'},
    {key:'11',value: 'Frijole', text:'Frijole'},
    {key:'12',value: 'FugazOne', text:'Fugaz One'},
    {key:'13',value: 'GreatVibes', text:'Great Vibes'},
    {key:'16',value: 'Monofett', text:'Monofett'},
    {key:'17',value: 'Monoton', text:'Monoton'},
    {key:'18',value: 'Montserrat', text:'Montserrat'},
    {key:'19',value: 'OdibeeSans', text:'Odibee Sans'},
    {key:'20',value: 'OpenSans', text:'Open Sans'},
    {key:'21',value: 'Orbitron', text:'Orbitron'},
    {key:'22',value: 'Oswald', text:'Oswald'},
    {key:'23',value: 'PirataOne', text:'Pirata One'},
    {key:'24',value: 'Raleway', text:'Raleway'},
    {key:'25',value: 'Roboto', text:'Roboto'},
    {key:'26',value: 'Rubik', text:'Rubik'},
];